name: ci

on:
  pull_request:

jobs:
  tests:
    permissions:
      checks: write
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Prisma generate
        run: yarn prisma generate

      - name: Run tests
        run: yarn test

      - name: Tests coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
