name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test
